#! /bin/bash

# determine the OS
# use a switch statement to determine command

egrep -i "svadmin |carpadmin" /etc/group

GROUPS=$(getent group |grep -i admin)
echo $GROUPS

OS=$(uname -o)

case $OS in
    GNU/Linux)
	echo "OS is $OS"
#	reset user passwd
	;;
#   Solaris)
#	;;
#   RHEL)
#	;;
#   SuSe)
#	;;
esac
